[package]
name = "voicegenerator"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
smol = "1.2.5"
surf = { version = "2.1.0", features = ["h1-client"], default-features = false }
tts-urls = "0.2.1"
