#!env bash
sox -n -r 24000 -c 1 silence.wav trim 0.0 3.0
ls -1 | grep "tts.*\.mp3" | sort -n | sed -z s/\\n/\\nsilence.wav\\n/g | xargs sh -c 'sox $@ out.mp3' sh
ls -1 | grep "[^(output)]\.mp3" | xargs rm
rm silence.wav